import { Iusers } from "../model/users";

export const users : Array<Iusers> = [
  {
    userName: 'May Doe',
    userId: '125',
    userRole: 'Candidate',
    profileDescription: 'Frontend developer with Angular experience.',
    profileImage: 'https://randomuser.me/api/portraits/men/32.jpg',
    skills: ['Angular', 'TypeScript', 'HTML', 'CSS'],
    experienceYears: 2,
    isActive: true,
    address: {
      current: {
        city: 'Pune',
        state: 'Maharashtra',
        country: 'India',
        zipcode: '411001',
      },
      permanent: {
        city: 'Latur',
        state: 'Maharashtra',
        country: 'India',
        zipcode: '413512',
      },
    },
  },
  {
    userName: 'Rahul Sharma',
    userId: '126',
    userRole: 'Candidate',
    profileDescription: 'Node.js backend developer working with MongoDB.',
    profileImage: 'https://randomuser.me/api/portraits/men/45.jpg',
    skills: ['Node.js', 'Express', 'MongoDB'],
    experienceYears: 3,
    isActive: true,
    address: {
      current: {
        city: 'Mumbai',
        state: 'Maharashtra',
        country: 'India',
        zipcode: '400001',
      },
      permanent: {
        city: 'Nagpur',
        state: 'Maharashtra',
        country: 'India',
        zipcode: '440001',
      },
    },
  },
  {
    userName: 'Sneha Gupta',
    userId: '127',
    userRole: 'HR',
    profileDescription: 'HR executive handling recruitment and onboarding.',
    profileImage: 'https://randomuser.me/api/portraits/women/44.jpg',
    skills: ['Recruitment', 'Communication', 'MS Excel'],
    experienceYears: 4,
    isActive: true,
    address: {
      current: {
        city: 'Hyderabad',
        state: 'Telangana',
        country: 'India',
        zipcode: '500001',
      },
      permanent: {
        city: 'Nanded',
        state: 'Maharashtra',
        country: 'India',
        zipcode: '431601',
      },
    },
  },
  {
    userName: 'Amit Pandey',
    userId: '128',
    userRole: 'Admin',
    profileDescription: 'System administrator managing infrastructure.',
    profileImage: 'https://randomuser.me/api/portraits/men/76.jpg',
    skills: ['Linux', 'Networking', 'AWS'],
    experienceYears: 5,
    isActive: false,
    address: {
      current: {
        city: 'Bangalore',
        state: 'Karnataka',
        country: 'India',
        zipcode: '560001',
      },
      permanent: {
        city: 'Solapur',
        state: 'Maharashtra',
        country: 'India',
        zipcode: '413001',
      },
    },
  },
  {
    userName: 'Pooja Tiwari',
    userId: '129',
    userRole: 'Candidate',
    profileDescription: 'UI/UX designer with Figma and Adobe XD experience.',
    profileImage: 'https://randomuser.me/api/portraits/women/68.jpg',
    skills: ['Figma', 'Adobe XD', 'Wireframing'],
    experienceYears: 3,
    isActive: true,
    address: {
      current: {
        city: 'Pune',
        state: 'Maharashtra',
        country: 'India',
        zipcode: '411002',
      },
      permanent: {
        city: 'Kolhapur',
        state: 'Maharashtra',
        country: 'India',
        zipcode: '416003',
      },
    },
  },
  {
    userName: 'Vikas Sharma',
    userId: '130',
    userRole: 'Candidate',
    profileDescription: 'Full stack developer working on MEAN stack.',
    profileImage: 'https://randomuser.me/api/portraits/men/30.jpg',
    skills: ['Angular', 'Node.js', 'MongoDB', 'Express'],
    experienceYears: 4,
    isActive: true,
    address: {
      current: {
        city: 'Nashik',
        state: 'Maharashtra',
        country: 'India',
        zipcode: '422001',
      },
      permanent: {
        city: 'Aurangabad',
        state: 'Maharashtra',
        country: 'India',
        zipcode: '431001',
      },
    },
  },
  {
    userName: 'Kiran Patil',
    userId: '131',
    userRole: 'Manager',
    profileDescription: 'Project manager handling multiple web projects.',
    profileImage: 'https://randomuser.me/api/portraits/women/90.jpg',
    skills: ['Project Management', 'Agile', 'Scrum'],
    experienceYears: 7,
    isActive: true,
    address: {
      current: {
        city: 'Delhi',
        state: 'Delhi',
        country: 'India',
        zipcode: '110001',
      },
      permanent: {
        city: 'Jaipur',
        state: 'Rajasthan',
        country: 'India',
        zipcode: '302001',
      },
    },
  },
  {
    userName: 'Neha Choudhary',
    userId: '132',
    userRole: 'Candidate',
    profileDescription:
      'QA engineer experienced in manual and automation testing.',
    profileImage: 'https://randomuser.me/api/portraits/women/22.jpg',
    skills: ['Selenium', 'Manual Testing', 'API Testing'],
    experienceYears: 3,
    isActive: false,
    address: {
      current: {
        city: 'Chennai',
        state: 'Tamil Nadu',
        country: 'India',
        zipcode: '600001',
      },
      permanent: {
        city: 'Madurai',
        state: 'Tamil Nadu',
        country: 'India',
        zipcode: '625001',
      },
    },
  },
  {
    userName: 'Arjun Mishra',
    userId: '133',
    userRole: 'Candidate',
    profileDescription: 'Data analyst working with Python and Power BI.',
    profileImage: 'https://randomuser.me/api/portraits/men/65.jpg',
    skills: ['Python', 'Power BI', 'SQL'],
    experienceYears: 2,
    isActive: true,
    address: {
      current: {
        city: 'Indore',
        state: 'Madhya Pradesh',
        country: 'India',
        zipcode: '452001',
      },
      permanent: {
        city: 'Bhopal',
        state: 'Madhya Pradesh',
        country: 'India',
        zipcode: '462001',
      },
    },
  },
];
